[package]
name = "token"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.1.1"
uint = { version = "0.9.3", default-features = false }
serde = "1"
serde_json = "1"